version: '3.9'

services:
  bin-user:
    build:
      context: .
      dockerfile: ./docker/services/dockerfile
      args:
        - SERVICE=user
        - PRESET=dev-posix
    volumes:
      - ./configs/:/ucu-bank/configs/:ro
    depends_on:
      - mongo-db

  bin-account:
    build:
      context: .
      dockerfile: ./docker/services/dockerfile
      args:
        - SERVICE=account
        - PRESET=dev-posix
    volumes:
      - ./configs/:/ucu-bank/configs/:ro
    depends_on:
      - bin-user

  bin-transaction:
    build:
      context: .
      args:
        - SERVICE=transaction
        - PRESET=dev-posix
      dockerfile: ./docker/services/dockerfile
    volumes:
      - ./configs/:/ucu-bank/configs/:ro
    depends_on:
      - postgres-db
      - bin-account

  bin-auth:
    build:
      context: .
      dockerfile: ./docker/services/dockerfile
      args:
        - SERVICE=auth
        - PRESET=dev-posix
    volumes:
      - ./configs/:/ucu-bank/configs/:ro
      - ~/.aws:/root/.aws:ro
    depends_on:
      - bin-user
      - auth-hash

  bin-gateway:
    build:
      context: .
      dockerfile: ./docker/services/dockerfile
      args:
        - SERVICE=gateway
        - PRESET=dev-posix
    volumes:
      - ./configs/:/ucu-bank/configs/:ro
      - ./configs/gateway/gateway_config.json:/ucu-bank/gateway_config.json:ro
      - /ucu-bank/logs
    depends_on:
      - bin-auth
      - bin-transaction
      - bin-account
      - bin-user
    ports:
      - 2020:2020
  
  auth-hash:
    image: redis

  mongo-db:
    build: docker/mongo-db/
    command: ["mongod", "--replSet", "r0", "--bind_ip", "localhost,mongo-db"]

  postgres-db:
    build: ./docker/postgres-db/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transactions