from .config import DEPENDENCIES, TRIPLET, CONFIG_PRESETS, BUILD_PRESETS
from .port import cmd_t_split
from .cmds import FETCH_SUBMODULES_CMD, INIT_VCPKG_CMD, INSTALL_PKG_CMD_T, CMAKE_CONFIGURE_CMD_T, CMAKE_BUILD_CMD_T