#ifndef UCU_BANK_STATUC_HPP
#define UCU_BANK_STATUC_HPP

enum TransactionStatus {
    OK = 0,
    TRANSACTION_FORBIDEN = 1,
    ACCOUNT_DOESNT_EXISTS = 2,
    TRANSACTION_FAILED = 3,
    IS_NOT_LOGINED = 4,
    NOT_ENOUGH_MONEY = 5,
};

#endif //UCU_BANK_STATUC_HPP
