FROM fedora:35

ENV VCPKG_ROOT=/home/vcpkg
RUN mkdir ${VCPKG_ROOT}

RUN dnf install -y git curl zip unzip tar cmake make g++ perl python3
RUN git clone https://github.com/Microsoft/vcpkg.git ${VCPKG_ROOT}
RUN ${VCPKG_ROOT}/bootstrap-vcpkg.sh

COPY vcpkg_install.py /home